### PR TITLE
Structured fact values as shown as pretty-printed, colored JSON + some bugs fixed

### LINKED ISSUE #612: Numerical facts don't get filtered properly
I noticed an issue with trying to filter numeric facts. For example I need to track version upgrades for our 600 Windows 10 PCs so I use the /fact/windows_release_id fact. If I want to view version 1909 for example, I would put /fact/windows_release_id/1909. However when I do this, it shows me all Windows 10's regardless of version number. I instead have to use the search box and type in "1909" to get the filter I need.

### PR DESCRIPTION
**Pull request by gdubicki**
#643 + #644

Fixes  #612 and #567 and (I think that) it implements #83.

Here's a screenshot of how will the complex facts look: https://github.com/voxpupuli/puppetboard/pull/644#issuecomment-974807389

### CODE REVIEW

**Review by sebastianrakel — APPROVED** [review]

**Comment by bastelfreak** [comment]
some of the commits here don't prepare the release but fix bugs or add features. Can you please provide those as dedicated PRs?

File: puppetboard/static/js/pretty.js [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+
+        if (is_complex) {
+            // Add pre tag for indentation to be visible
+            to_show = '<pre>' + to_show + '</pre>'
+        }
+
+    }
+
+    return to_show
+}
```
Comment (bastelfreak) [inline puppetboard/static/js/pretty.js:42]: please add the missing newline here

Comment (gdubicki) [reply puppetboard/static/js/pretty.js]: Added, thanks!

**Review by bastelfreak — APPROVED** [review]
